### ISSUE TITLE
Inconsistent method naming convention

### ISSUE THREAD

**Issue by adelowo** [silk8192/libcache#1]
All methods in the library make use of `snake_case` except the `invalidateAll` method (camelcase).

Relevant links -

 https://github.com/silk8192/libcache/blob/master/lib/libcache/cache.rb#L83-L85
https://github.com/silk8192/libcache/blob/master/lib/libcache/file_cache.rb#L61-L66

**Comment by salahsheikh** [comment]
aha its the java conventions creeping in. I'll rename it ASAP.

**Comment by adelowo** [comment]
Nice to hear that

**Comment by salahsheikh** [comment]
fixed by #2
